name: Code style check

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  job_lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Lint src
        uses: DoozyX/clang-format-lint-action@c71d0bf4e21876ebec3e5647491186f8797fde31 # v0.13
        with:
          source: './src'
          extensions: 'h,c'
          clangFormatVersion: 12.0.0

      - name: Lint libsol
        uses: DoozyX/clang-format-lint-action@c71d0bf4e21876ebec3e5647491186f8797fde31 # v0.13
        with:
          source: './libsol'
          extensions: 'h,c'
          clangFormatVersion: 12.0.0

  misspell:
    name: Check misspellings
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Check misspellings
        uses: codespell-project/actions-codespell@22ff5a2e4b591290baf82d47c9feadac31c65441 # v1
        with:
          builtin: clear,rare
          check_filenames: true
          path: src/,libsol/,Makefile,README.md,doc/
          skip: ./libsol/printer_test.c
