name: GitHub release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  packages: read

jobs:
  github-release:
    name: GitHub release using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_app_release.yml@adb54f0c6a2fa93a7f14764f92ad4d09cc4f192a # v1
    if: startsWith(github.ref, 'refs/tags/')
    with:
      app_ref_name: ${{ github.ref_name }}
